services:
    myjd-api:
        image: ghcr.io/zarvelionzynji/myjd-api:latest
        container_name: myjd-api
        ports:
            - 8069:5000
        environment:
            - JD_EMAIL=your@email
            - JD_PASSWORD=your_password
            - JD_DEVICE=your_device
        restart: unless-stopped
